# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skCJJh69g8Lh1XAbeTc4xJNihsa8Q42w
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

df=pd.read_csv('Automobile_data.csv')

df

df.head()

df.describe()

df.replace('?', np.nan, inplace=True)

df

print(df.columns[df.isnull().any()])

df.dropna(subset=['price'], inplace=True)

print(df.isnull().sum())

num_cols = ['normalized-losses', 'bore', 'stroke', 'horsepower', 'peak-rpm']
for col in num_cols:
    df[col].fillna(df[col].astype(float).mean(), inplace=True)
df['num-of-doors'].fillna(df['num-of-doors'].mode()[0], inplace=True)

df

print(df.isnull().sum())

categorical_cols = df.select_dtypes(include=['object']).columns
print(categorical_cols)

for col in df.columns:
    if df[col].dtype == 'object' or df[col].dtype.name == 'category':
        print(f"{col} -> {df[col].nunique()} unique values")

categorical_cols = ['make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels',
                    'engine-location', 'engine-type', 'num-of-cylinders', 'fuel-system']

data = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

X = data.drop('price', axis=1)
y = data['price'].astype(float)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = r2_score(y_test, y_pred) * 100

print(f'Accuracy: {accuracy:.2f}%')

feature_importance = pd.Series(model.coef_, index=X.columns).sort_values(ascending=False)

print(feature_importance)

